// Structural data only; the human-facing label/why/badge text lives in i18n.js
// (gallery.items.<id> and gallery.badge.<badge>) so it can be translated.
export const EXAMPLES = [
  // ---- good (multi-step / widget; criterion makes the run show "verified") ----
  { id: "pydocs-json", group: "good", badge: "verified",
    task: "On docs.python.org, open The Python Standard Library, then open the documentation page for the json module.",
    url: "https://docs.python.org/3/", criterion: { url_contains: "library/json" } },
  { id: "wiki-autocomplete", group: "good", badge: "verified",
    task: "On Wikipedia, type 'Argon' into the search box and choose 'Argon' from the autocomplete suggestions that appear, to open its article.",
    url: "https://en.wikipedia.org/wiki/Main_Page", criterion: { h1_equals: "Argon" } },
  { id: "hn-show-ask", group: "good", badge: "verified",
    task: "Starting from the Hacker News front page, first open the Show HN section, then from there navigate to the Ask HN section.",
    url: "https://news.ycombinator.com/", criterion: { url_contains: "/ask" } },
  { id: "govuk-driving", group: "good", badge: "verified",
    task: "Starting from the GOV.UK homepage, open the 'Driving and transport' browse section, then go into its 'Driving licences' subtopic.",
    url: "https://www.gov.uk/", criterion: { url_contains: "browse/driving/driving-licences" } },
  { id: "amazon-headless", group: "good", badge: "verified",
    task: "On amazon.com, search for 'usb c cable' and open the first result.",
    url: "https://www.amazon.com/", criterion: { url_contains: "/dp/" } },
  { id: "internet-modal", group: "good", badge: "verified",
    task: "Open this page where a modal window appears, and read the modal window's title.",
    url: "https://the-internet.herokuapp.com/entry_ad",
    criterion: { selector_text_equals: { css: ".modal-title h3", value: "This is a modal window" } } },
  // ---- limitation (the agent abstains / fails closed) ----
  { id: "internet-iframe", group: "limitation", badge: "abstain",
    task: "On this page, type 'browser agent was here' into the rich-text editor inside the iframe.",
    url: "https://the-internet.herokuapp.com/iframe" },
  { id: "github-login", group: "limitation", badge: "abstain",
    task: "Sign in to your GitHub account.", url: "https://github.com/login" },
  { id: "recaptcha", group: "limitation", badge: "abstain",
    task: "On this page, fill in the form fields and submit it.",
    url: "https://www.google.com/recaptcha/api2/demo" },
  { id: "g2-datadome", group: "limitation", badge: "blocked",
    task: "Open the marketing software category page on g2.com.", url: "https://www.g2.com/" },
  { id: "cloudflare-wall", group: "limitation", badge: "blocked",
    task: "Open this page and read the main heading.", url: "https://nowsecure.nl/" },
];
