// Structural data only; the human-facing label/why/badge text lives in i18n.js
// (gallery.items.<id> and gallery.badge.<badge>) so it can be translated.
export const EXAMPLES = [
  // ---- good (multi-step / widget; criterion makes the run show "verified") ----
  { id: "pydocs-json", group: "good", badge: "verified",
    task: "On docs.python.org, open The Python Standard Library, then open the documentation page for the json module.",
    url: "https://docs.python.org/3/", criterion: { url_contains: "library/json" } },
  { id: "wiki-autocomplete", group: "good", badge: "verified",
    task: "On Wikipedia, type 'Argon' into the search box and choose 'Argon' from the autocomplete suggestions that appear, to open its article.",
    url: "https://en.wikipedia.org/wiki/Main_Page", criterion: { h1_equals: "Argon" } },
  { id: "hn-show-ask", group: "good", badge: "verified",
    task: "On Hacker News, use the small links in the top bar (new, past, comments, ask, show, jobs) — NOT the article headlines in the list below. First click the 'show' link to open the Show HN page, then on that page click the 'ask' link in the same top bar to open the Ask HN page.",
    url: "https://news.ycombinator.com/", criterion: { url_contains: "/ask" } },
  { id: "govuk-driving", group: "good", badge: "verified",
    task: "Starting from the GOV.UK homepage, open the 'Driving and transport' browse section, then go into its 'Driving licences' subtopic.",
    url: "https://www.gov.uk/", criterion: { url_contains: "browse/driving/driving-licences" } },
  { id: "amazon-headless", group: "good", badge: "verified",
    task: "On amazon.com, search for 'usb c cable' and open the first result.",
    url: "https://www.amazon.com/", criterion: { url_contains: "/dp/" } },
  { id: "internet-modal", group: "good", badge: "verified",
    task: "Open this page where a modal window appears, and read the modal window's title.",
    url: "https://the-internet.herokuapp.com/entry_ad",
    criterion: { selector_text_equals: { css: ".modal-title h3", value: "This is a modal window" } } },
  // ---- good: finance/stock cases (autoresearch, non-anti-bot sites) ----
  { id: "sa-balance-sheet", group: "good", badge: "verified",
    task: "On stockanalysis.com, open Apple's stock page and then navigate to its Balance Sheet under the Financials section.",
    url: "https://stockanalysis.com/", criterion: { url_contains: "financials/balance-sheet" } },
  { id: "cmc-compare", group: "good", badge: "verified",
    task: "On companiesmarketcap.com, determine whether NVIDIA or Apple has the larger market capitalization, then open the market-cap detail page of whichever is larger.",
    url: "https://companiesmarketcap.com/", criterion: { url_contains: "/nvidia/marketcap" } },
  { id: "screenerin-company-metric", group: "good", badge: "verified",
    task: "On screener.in, search for Tata Consultancy Services (TCS), open its company page, and read its ROCE figure.",
    url: "https://www.screener.in/", criterion: { url_contains: "/company/TCS" } },
  // ---- limitation (the agent abstains / fails closed) ----
  { id: "internet-iframe", group: "limitation", badge: "abstain",
    task: "On this page, type 'browser agent was here' into the rich-text editor inside the iframe.",
    url: "https://the-internet.herokuapp.com/iframe" },
  { id: "recaptcha", group: "limitation", badge: "abstain",
    task: "On this page, fill in the form fields and submit it.",
    url: "https://www.google.com/recaptcha/api2/demo" },
  { id: "g2-datadome", group: "limitation", badge: "blocked",
    task: "Open the marketing software category page on g2.com.", url: "https://www.g2.com/" },
  { id: "cloudflare-wall", group: "limitation", badge: "blocked",
    task: "Open this page and read the main heading.", url: "https://nowsecure.nl/" },
  { id: "screenerin-loginwall", group: "limitation", badge: "abstain",
    task: "On screener.in, open the 'Highest Dividend Yield Shares' screen and sort the result table by P/E ratio.",
    url: "https://www.screener.in/screens/3/highest-dividend-yield-shares/" },
];
