// Structural data only; the human-facing label/why/badge text lives in i18n.js
// (gallery.items.<id> and gallery.badge.<badge>) so it can be translated.
export const EXAMPLES = [
  // ---- good (multi-step / widget; criterion makes the run show "verified") ----
  { id: "pydocs-json", group: "good", badge: "verified",
    task: "On docs.python.org, open The Python Standard Library, then open the documentation page for the json module.",
    url: "https://docs.python.org/3/", criterion: { url_contains: "library/json" } },
  { id: "wiki-autocomplete", group: "good", badge: "verified",
    task: "On Wikipedia, type 'Argon' into the search box and choose 'Argon' from the autocomplete suggestions that appear, to open its article.",
    url: "https://en.wikipedia.org/wiki/Main_Page", criterion: { h1_equals: "Argon" } },
  { id: "govuk-driving", group: "good", badge: "verified",
    task: "Starting from the GOV.UK homepage, open the 'Driving and transport' browse section, then go into its 'Driving licences' subtopic.",
    url: "https://www.gov.uk/", criterion: { url_contains: "browse/driving/driving-licences" } },
  { id: "amazon-headless", group: "good", badge: "verified",
    task: "On amazon.com, search for 'usb c cable' and open the first result.",
    url: "https://www.amazon.com/", criterion: { url_contains: "/dp/" } },
  { id: "internet-modal", group: "good", badge: "verified",
    task: "Open this page where a modal window appears, and read the modal window's title.",
    url: "https://the-internet.herokuapp.com/entry_ad",
    criterion: { selector_text_equals: { css: ".modal-title h3", value: "This is a modal window" } } },
  { id: "httpbin-form-fill", group: "good", badge: "verified",
    task: "On this pizza order form, fill Customer name 'Ada Lovelace', Telephone '5551234', E-mail address 'ada@example.com', choose Pizza Size 'Large', check the 'Bacon' and 'Mushroom' toppings, set Delivery instructions to 'leave at the door', then submit the order.",
    url: "https://httpbin.org/forms/post", criterion: { url_contains: "httpbin.org/post" } },
  // ---- good: finance/stock cases (autoresearch, non-anti-bot sites) ----
  { id: "sa-balance-sheet", group: "good", badge: "verified",
    task: "On stockanalysis.com, open Apple's stock page and then navigate to its Balance Sheet under the Financials section.",
    url: "https://stockanalysis.com/", criterion: { url_contains: "financials/balance-sheet" } },
  { id: "sa-pe-compare-drilldown", group: "good", badge: "verified",
    task: "On stockanalysis.com, determine whether NVIDIA (NVDA) or JPMorgan Chase (JPM) has the higher P/E ratio, then open the Balance Sheet (under the Financials section) of whichever company has the higher P/E.",
    url: "https://stockanalysis.com/", criterion: { url_contains: "/nvda/financials/balance-sheet" } },
  { id: "screenerin-company-metric", group: "good", badge: "verified",
    task: "On screener.in, search for Tata Consultancy Services (TCS), open its company page, and read its ROCE figure.",
    url: "https://www.screener.in/", criterion: { url_contains: "/company/TCS" } },
  // ---- good: rubric-targeted hard cases (silent-failure / self-correction) ----
  { id: "todomvc-add-complete", group: "good", badge: "verified",
    task: "Add three to-do items by typing each into the input box and pressing Enter (there is no Add button): first 'buy milk', then 'walk dog', then 'write report'. Then mark the second item ('walk dog') as completed, and click the 'Active' filter.",
    url: "https://todomvc.com/examples/javascript-es6/dist/",
    criterion: { selector_text_equals: { css: ".todo-count", value: "2 items left" } } },
  { id: "uitap-ajax", group: "good", badge: "verified",
    task: "Click the 'Button Triggering AJAX Request' button, then wait for the green success message to appear.",
    url: "http://uitestingplayground.com/ajax",
    criterion: { selector_text_equals: { css: "#content", value: "Data loaded with AJAX get request." } } },
  { id: "internet-dynamic-controls", group: "good", badge: "verified",
    task: "In the first example (Remove/Add), click 'Remove' and wait until the checkbox is removed.",
    url: "https://the-internet.herokuapp.com/dynamic_controls",
    criterion: { selector_text_equals: { css: "#message", value: "It's gone!" } } },
  // ---- limitation (the agent abstains / fails closed) ----
  { id: "internet-iframe", group: "limitation", badge: "abstain",
    task: "On this page, type 'browser agent was here' into the rich-text editor inside the iframe.",
    url: "https://the-internet.herokuapp.com/iframe" },
  { id: "recaptcha", group: "limitation", badge: "abstain",
    task: "On this page, fill in the form fields and submit it.",
    url: "https://www.google.com/recaptcha/api2/demo" },
  { id: "g2-datadome", group: "limitation", badge: "blocked",
    task: "Open the marketing software category page on g2.com.", url: "https://www.g2.com/" },
  { id: "cloudflare-wall", group: "limitation", badge: "blocked",
    task: "Open this page and read the main heading.", url: "https://nowsecure.nl/" },
  { id: "screenerin-loginwall", group: "limitation", badge: "abstain",
    task: "On screener.in, open the 'Highest Dividend Yield Shares' screen and sort the result table by P/E ratio.",
    url: "https://www.screener.in/screens/3/highest-dividend-yield-shares/" },
];
